# windowrule = tag +multimedia_video, class:^([Mm]pv|vlc)$
# windowrule = tag +settings, class:^(nm-applet|nm-connection-editor|blueman-manager|FileRoller)$
# windowrule = tag +settings, class:^(DiskUtility|wihotspot(-gui)?)$
# # windowrule = tag +viewer, class:^(SystemMonitor)$ # system monitor
# windowrule = tag +viewer, class:^(Evince)$ # document viewer
# windowrule = tag +viewer, class:^(gwenview)$ # image viewer
